// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnuchfpmrwxtjyvwlujg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNudWNoZnBtcnd4dGp5dndsdWpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNzkwNjksImV4cCI6MjA2MDY1NTA2OX0.93fkWWEh8SYYF9-MiCkFABu9YqOAWc2LIs5tH7j1Rzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);